apiVersion: v1
kind: Service
metadata:
  name: study-buddy-service
  namespace: streamlit
spec:
  selector:
    app: study-buddy
  ports:
    - protocol: TCP
      port: 8119
      targetPort: 8501